// <auto-generated />
using Final.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final.Migrations
{
    [DbContext(typeof(EntertainmentInfoContext))]
    [Migration("20230424204658_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Final.Models.Entertainers", b =>
                {
                    b.Property<int>("EntertainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateEntered")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntEMailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntSSN")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntStageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntState")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntStreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntWebPage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("EntertainerID");

                    b.ToTable("Entertainers");
                });
#pragma warning restore 612, 618
        }
    }
}
