// <auto-generated />
using MIssion6DevonWolsleger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MIssion6DevonWolsleger.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230221180128_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MIssion6DevonWolsleger.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CatagoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            CatagoryId = 1,
                            Director = "Quinten Tarentino",
                            Edited = false,
                            Rating = "R",
                            Title = "Kill Bill",
                            Year = 2003
                        },
                        new
                        {
                            ApplicationId = 2,
                            CatagoryId = 1,
                            Director = "George Lucas",
                            Edited = false,
                            Rating = "PG",
                            Title = "Star Wars Episode I: The Phantom Menace",
                            Year = 1999
                        },
                        new
                        {
                            ApplicationId = 3,
                            CatagoryId = 2,
                            Director = "Larry Morey",
                            Edited = false,
                            Rating = "G",
                            Title = "Snow White and the Seven Dwarfs",
                            Year = 1938
                        });
                });

            modelBuilder.Entity("MIssion6DevonWolsleger.Models.Catagory", b =>
                {
                    b.Property<int>("CatagoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatagoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CatagoryId");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CatagoryId = 1,
                            CatagoryName = "Action"
                        },
                        new
                        {
                            CatagoryId = 2,
                            CatagoryName = "Adventure"
                        },
                        new
                        {
                            CatagoryId = 3,
                            CatagoryName = "Romance"
                        },
                        new
                        {
                            CatagoryId = 4,
                            CatagoryName = "Thriller"
                        },
                        new
                        {
                            CatagoryId = 5,
                            CatagoryName = "Horror"
                        });
                });

            modelBuilder.Entity("MIssion6DevonWolsleger.Models.ApplicationResponse", b =>
                {
                    b.HasOne("MIssion6DevonWolsleger.Models.Catagory", "Catagory")
                        .WithMany()
                        .HasForeignKey("CatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
